-- 船期表数据库表结构
-- 创建 schedule_table 表

CREATE TABLE IF NOT EXISTS schedule_table (
  id INT AUTO_INCREMENT PRIMARY KEY,
  vessel VARCHAR(100) NOT NULL COMMENT '船名',
  eta VARCHAR(20) NOT NULL COMMENT '预计到达时间',
  pol VARCHAR(255) NOT NULL COMMENT '装货港',
  pod TEXT NOT NULL COMMENT '卸货港(可以有多个)',
  route VARCHAR(50) NOT NULL COMMENT '航线',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='船期表';

-- 插入示例数据
INSERT INTO schedule_table (vessel, eta, pol, pod, route) VALUES
('STRADION', '01-06', 'TIANJIN', 'JAKARTA', '东阿亚'),
('CP GIXON', '01-08', 'TIANJIN', 'MUMBAI, MUNDRA', '印度'),
('QUPULAI 18', '01-13', 'TIANJIN', 'VIZAG, KOLKATA', '印度'),
('ZHE HAI 526', '01-07', 'TIANJIN, LYG', 'JEDDAH, AQABA', '中东'),
('GREAT WENTAO', '01-10', 'TIANJIN', 'KARACHI, KANDLA', '中东'),
('SEA PRAJNA', '01-10', 'TIANJIN, LYG', 'DJIBOUTI, SUDAN, AQABA', '中东'),
('GRAMMY BRAVE', '01-13', 'TIANJIN, SHANGHAI', 'ABBAS', '中东'),
('KSL QINGYANG', '01-18', 'TIANJIN', 'UMM QASR, KUWAIT', '中东'),
('KSL DEYANG', '01-20', 'TIANJIN, SHANGHAI', 'ISKENDERUN, BOURGAS, DILISKELESI', '中东'),
('HG BREMEN', '01-07', 'TIANJIN, SHANGHAI', 'DURBAN, MANAUS', '非洲'),
('TOP DILIGENCE', '01-08', 'TIANJIN', 'DOUALA, WARRI, KRIBI', '非洲'),
('BAO RI LING', '01-08', 'TIANJIN', 'POINTE NOIRE, LUANDA, MATADI', '非洲'),
('ABUNDANCE', '01-09', 'TIANJIN, LYG', 'DJIBOUTI, JEDDAH, SUDAN, AQABA', '非洲'),
('BAO FLOURISH', '01-10', 'TIANJIN', 'DJEN DJEN', '非洲'),
('PACIFIC WEALTH', '01-10', 'TIANJIN, LYG', 'LAGOS, DOUALA', '非洲'),
('ATLANTIC VISION', '01-13', 'TIANJIN', 'NOUAKCHOTT, DAKAR', '非洲'),
('ZH ZHONG XING', '01-24', 'TIANJIN', 'TANGA, DURBAN', '非洲'),
('CBC DRAGON', '01-10', 'TIANJIN', 'CORINTO, QUETZAL', '南美'),
('OCEAN TIANBO', '01-11', 'BYQ, TIANJIN', 'BUENAVENTURA, GUAYAQUIL', '南美'),
('EASTERN GARDENIA', '01-12', 'CHANGSHU, TIANJIN', 'CALLAO, MATARANI', '南美'),
('PACIFIC LILY', '01-12', 'BYQ, TIANJIN', 'GUAYAQUIL, VLP', '南美'),
('MEREL D', '01-12', 'TIANJIN', 'GUAYAQUIL, VLP', '南美'),
('WEN LI', '01-13', 'BYQ, TIANJIN', 'CRISTOBAL, RIO HAINA, BARRANQUILLA', '南美'),
('YIN NENG', '01-13', 'TIANJIN', 'BUENAVENTURA, CALLAO, VLP', '南美'),
('XIN HAI TONG 26', '01-15', 'TIANJIN', 'ACAJUTLA, LIMON, BARRANQUILLA', '南美'),
('VELA', '01-15', 'TIANJIN', 'CALLAO, GUAYAQUIL, SAN LORENZO', '南美');
